version: '2.1'
services:
  couchbase:
    image: couchbase/server:community-4.5.0
    hostname: db.anno
    volumes:
      - data:/opt/couchbase/var
    ports:
      # 8091: Couchbase Web console, REST/HTTP interface
      # 8092: Views, queries, XDCR
      # 8093: Query services (4.0+)
      # 8094: Full-text Serarch (4.5+)
      # 11207: Smart client library data node access (SSL)
      # 11210: Smart client library/moxi data node access
      # 11211: Legacy non-smart client library data node access
      # 18091: Couchbase Web console, REST/HTTP interface (SSL)
      # 18092: Views, query, XDCR (SSL)
      # 18093: Query services (SSL) (4.0+)
      - 20001-20004:8091-8094
      - 20005:11207
      - 20006:11210
      - 20007:11211
      - 20008-20010:18091-18093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/"]
      interval: 5s
      timeout: 5s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: config/docker/backend.Dockerfile
    hostname: app.anno
    volumes:
      - bundle:/bundle
      - .:/app
    ports:
      - 3000:3000
    environment:
      - LCB_OPTIONS=detailed_errcodes=1
    links:
      - couchbase:db.anno
    depends_on:
      couchbase:
        condition: service_healthy
volumes:
  data:
  bundle:
