version: '2'
services:
  couchbase:
    image: couchbase/server:community-4.5.0
    hostname: anno_db
    volumes:
      - data:/opt/couchbase/var
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  backend:
    build:
      context: .
      dockerfile: config/docker/backend.Dockerfile
    hostname: anno_backend
    volumes:
      - bundle:/bundle
      - .:/app
    links:
      - couchbase
    ports:
      - 3000:3000
volumes:
  data:
  bundle:
